apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django
spec:
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer  # Expose service to Minikube