apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 3  # Multiple instances
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: anhbuiliferay/django-web:latest
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        envFrom:
        - configMapRef:
            name: django-config
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer  # Expose service to Minikube
