apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.15.1
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: xpack.security.enabled
          value: "false"
        - name: cluster.routing.allocation.disk.watermark.flood_stage
          value: "5gb"
        - name: cluster.routing.allocation.disk.watermark.high
          value: "10gb"
        - name: cluster.routing.allocation.disk.watermark.low
          value: "15gb"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: esdata
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: esdata
        emptyDir: {}
